# Generated by cucumber-sinatra. (2012-10-08 12:38:30 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/twit_sort.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = twitsort

class twitsortWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  twitsortWorld.new
end
